# Generated by Django 3.2 on 2021-04-11 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUserModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='commonusers', serialize=False, to='accounts.usermodel')),
                ('phone_number', models.CharField(max_length=20, null=True, unique=True)),
                ('picture', models.ImageField(default='commonuser/default/default_commonuser.jpg', upload_to='commonuser/coverpicture')),
            ],
        ),
    ]
